
#include "demo-unistd.h"

/* Autogenerated code from the defintions in unistd.h */

_syscall0(int,idle)
_syscall1(int,clone,int,flags)
_syscall0(int,pause)
_syscall0(int,sync)
_syscall0(pid_t,setsid)
_syscall3(int,write,int,fd,const char *,buf,off_t,count)
_syscall3(int,read,int,fd,char *,buf,off_t,count)
_syscall3(off_t,lseek,int,fd,off_t,offset,int,count)
_syscall1(int,dup,int,fd)
_syscall3(int,execve,const char *,file,char **,argv,char **,envp)
_syscall3(int,open,const char *,file,int,flag,int,mode)
_syscall1(int,close,int,fd)
// _syscall1(int,_exit,int,exitcode)
_syscall3(pid_t,waitpid,pid_t,pid,int *,wait_stat,int,options)
_syscall1(int,delete_module,const char *,name)

pid_t wait(int * wait_stat)
{
	return waitpid(-1,wait_stat,0);
}
